-- Create related_animes table
CREATE TABLE IF NOT EXISTS public.related_animes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_id TEXT NOT NULL REFERENCES public.animes("animeId") ON DELETE CASCADE,
    related_id TEXT NOT NULL,
    title TEXT NOT NULL,
    relation TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(anime_id, related_id, relation)
);

-- Enable RLS
ALTER TABLE public.related_animes ENABLE ROW LEVEL SECURITY;

-- Allow public read access
DROP POLICY IF EXISTS "Allow public read access" ON public.related_animes;
CREATE POLICY "Allow public read access" ON public.related_animes
    FOR SELECT USING (true);

-- Allow service role to manage
DROP POLICY IF EXISTS "Allow service role to manage" ON public.related_animes;
CREATE POLICY "Allow service role to manage" ON public.related_animes
    FOR ALL 
    TO service_role 
    USING (true) 
    WITH CHECK (true);

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON public.related_animes;
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.related_animes
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();
