-- Read-only public API model:
-- - API consumers only have SELECT permissions through RLS
-- - Scraper worker writes data using service_role

-- Shared trigger helper for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Feed table for anime listings (directory, latest, broadcast, rating)
CREATE TABLE IF NOT EXISTS public.anime_feed_items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	feed_type TEXT NOT NULL CHECK (feed_type IN ('directory', 'latest', 'broadcast', 'rating')),
	anime_id TEXT NOT NULL REFERENCES public.animes("animeId") ON DELETE CASCADE,
	page INTEGER NOT NULL DEFAULT 1 CHECK (page > 0),
	position INTEGER NOT NULL CHECK (position >= 0),
	feed_fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE (feed_type, page, position),
	UNIQUE (feed_type, anime_id, page)
);

CREATE INDEX IF NOT EXISTS idx_anime_feed_items_feed_page_position
ON public.anime_feed_items (feed_type, page, position);

CREATE INDEX IF NOT EXISTS idx_anime_feed_items_anime_id
ON public.anime_feed_items (anime_id);

-- Feed table for episode listings
CREATE TABLE IF NOT EXISTS public.episode_feed_items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	feed_type TEXT NOT NULL CHECK (feed_type IN ('latest')),
	episode_id TEXT NOT NULL REFERENCES public.episodes("episodeId") ON DELETE CASCADE,
	position INTEGER NOT NULL CHECK (position >= 0),
	feed_fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE (feed_type, position),
	UNIQUE (feed_type, episode_id)
);

CREATE INDEX IF NOT EXISTS idx_episode_feed_items_feed_position
ON public.episode_feed_items (feed_type, position);

-- Pre-calculated episode sources
CREATE TABLE IF NOT EXISTS public.episode_sources (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	episode_id TEXT NOT NULL UNIQUE REFERENCES public.episodes("episodeId") ON DELETE CASCADE,
	episode INTEGER NOT NULL DEFAULT 0,
	videos JSONB NOT NULL DEFAULT '[]'::jsonb,
	scraped_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	expires_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_episode_sources_episode_id
ON public.episode_sources (episode_id);

-- Worker synchronization state
CREATE TABLE IF NOT EXISTS public.sync_state (
	resource_type TEXT NOT NULL,
	resource_id TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'success', 'error')),
	last_success_at TIMESTAMPTZ,
	last_error_at TIMESTAMPTZ,
	error_count INTEGER NOT NULL DEFAULT 0,
	error_message TEXT,
	next_run_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (resource_type, resource_id)
);

-- updated_at triggers for new tables
DROP TRIGGER IF EXISTS set_updated_at_anime_feed_items ON public.anime_feed_items;
CREATE TRIGGER set_updated_at_anime_feed_items
	BEFORE UPDATE ON public.anime_feed_items
	FOR EACH ROW
	EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_episode_feed_items ON public.episode_feed_items;
CREATE TRIGGER set_updated_at_episode_feed_items
	BEFORE UPDATE ON public.episode_feed_items
	FOR EACH ROW
	EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_episode_sources ON public.episode_sources;
CREATE TRIGGER set_updated_at_episode_sources
	BEFORE UPDATE ON public.episode_sources
	FOR EACH ROW
	EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_sync_state ON public.sync_state;
CREATE TRIGGER set_updated_at_sync_state
	BEFORE UPDATE ON public.sync_state
	FOR EACH ROW
	EXECUTE FUNCTION public.handle_updated_at();

-- Enable RLS
ALTER TABLE public.animes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.related_animes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anime_feed_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episode_feed_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episode_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_state ENABLE ROW LEVEL SECURITY;

-- Remove old public write policies from core tables
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.animes;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.animes;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.episodes;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.episodes;

DROP POLICY IF EXISTS "Allow authenticated insert" ON public.related_animes;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.related_animes;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.related_animes;

-- Public read policies
DROP POLICY IF EXISTS "Allow public read access" ON public.anime_feed_items;
CREATE POLICY "Allow public read access" ON public.anime_feed_items
	FOR SELECT TO anon, authenticated, service_role
	USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.episode_feed_items;
CREATE POLICY "Allow public read access" ON public.episode_feed_items
	FOR SELECT TO anon, authenticated, service_role
	USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.episode_sources;
CREATE POLICY "Allow public read access" ON public.episode_sources
	FOR SELECT TO anon, authenticated, service_role
	USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.sync_state;
CREATE POLICY "Allow public read access" ON public.sync_state
	FOR SELECT TO anon, authenticated, service_role
	USING (true);

-- Service role write policies
DROP POLICY IF EXISTS "Allow service role to manage" ON public.animes;
CREATE POLICY "Allow service role to manage" ON public.animes
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role to manage" ON public.episodes;
CREATE POLICY "Allow service role to manage" ON public.episodes
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role to manage" ON public.related_animes;
CREATE POLICY "Allow service role to manage" ON public.related_animes
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role to manage" ON public.anime_feed_items;
CREATE POLICY "Allow service role to manage" ON public.anime_feed_items
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role to manage" ON public.episode_feed_items;
CREATE POLICY "Allow service role to manage" ON public.episode_feed_items
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role to manage" ON public.episode_sources;
CREATE POLICY "Allow service role to manage" ON public.episode_sources
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role to manage" ON public.sync_state;
CREATE POLICY "Allow service role to manage" ON public.sync_state
	FOR ALL TO service_role
	USING (true)
	WITH CHECK (true);
